# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftFrame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'Kingfisher'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Moya/RxSwift'
pod 'Moya'
pod 'HandyJSON'
pod 'MBProgressHUD'
pod 'MJRefresh'#pod 'MJRefresh', '~> 3.1.15.3'

pod 'RxDataSources'#pod 'RxDataSources', '~> 3.0.2'


end
